import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

// GET - List published blog posts with filters
export async function GET(request: NextRequest) {
  try {
    const supabase = await createClient();
    const { searchParams } = new URL(request.url);

    const game = searchParams.get("game");
    const category = searchParams.get("category");
    const tag = searchParams.get("tag");
    const author = searchParams.get("author");
    const featured = searchParams.get("featured") === "true";
    const search = searchParams.get("search");
    const limit = parseInt(searchParams.get("limit") || "20");
    const offset = parseInt(searchParams.get("offset") || "0");

    let query = supabase
      .from("blog_posts")
      .select(
        `
        id, title, slug, excerpt, featured_image_url, category, tags,
        published_at, views_count, likes_count, comments_count,
        is_featured, is_pinned,
        author:profiles!blog_posts_author_id_fkey(
          id, username, display_name, avatar_url
        ),
        game:games!blog_posts_game_id_fkey(
          id, slug, name, icon_url
        )
      `,
        { count: "exact" }
      )
      .eq("status", "published")
      .order("is_pinned", { ascending: false })
      .order("published_at", { ascending: false })
      .range(offset, offset + limit - 1);

    // Filter by game
    if (game) {
      const { data: gameData } = await supabase
        .from("games")
        .select("id")
        .eq("slug", game)
        .single();

      if (gameData) {
        query = query.eq("game_id", gameData.id);
      }
    }

    // Filter by category
    if (category) {
      query = query.eq("category", category);
    }

    // Filter by tag
    if (tag) {
      query = query.contains("tags", [tag]);
    }

    // Filter by author
    if (author) {
      const { data: authorData } = await supabase
        .from("profiles")
        .select("id")
        .eq("username", author)
        .single();

      if (authorData) {
        query = query.eq("author_id", authorData.id);
      }
    }

    // Filter featured only
    if (featured) {
      query = query.eq("is_featured", true);
    }

    // Search in title
    if (search) {
      query = query.ilike("title", `%${search}%`);
    }

    const { data, error, count } = await query;

    if (error) {
      console.error("Error fetching blog posts:", error);
      return NextResponse.json(
        { error: "Failed to fetch posts" },
        { status: 500 }
      );
    }

    return NextResponse.json({
      posts: data || [],
      total: count || 0,
      limit,
      offset,
    });
  } catch (error) {
    console.error("Blog list error:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}

// POST - Create new blog post
export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient();
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // Check if user is a blog author
    const { data: author } = await supabase
      .from("blog_authors")
      .select("id, can_publish_directly")
      .eq("user_id", user.id)
      .single();

    if (!author) {
      return NextResponse.json(
        { error: "You are not authorized to create blog posts" },
        { status: 403 }
      );
    }

    const body = await request.json();
    const {
      title,
      content,
      excerpt,
      featured_image_url,
      game_id,
      category,
      tags,
      status,
      meta_title,
      meta_description,
      allow_comments,
    } = body;

    // Validation
    if (!title || !content || !category) {
      return NextResponse.json(
        { error: "Title, content, and category are required" },
        { status: 400 }
      );
    }

    // Determine status based on author permissions
    let postStatus = status || "draft";
    if (postStatus === "published" && !author.can_publish_directly) {
      postStatus = "pending_review";
    }

    const publishedAt =
      postStatus === "published" ? new Date().toISOString() : null;

    // Create post (slug is generated by database trigger)
    const { data: post, error: postError } = await supabase
      .from("blog_posts")
      .insert({
        author_id: user.id,
        title: title.trim(),
        content,
        excerpt: excerpt?.trim() || null,
        featured_image_url: featured_image_url || null,
        game_id: game_id || null,
        category,
        tags: tags || [],
        status: postStatus,
        published_at: publishedAt,
        meta_title: meta_title || null,
        meta_description: meta_description || null,
        allow_comments: allow_comments !== false,
      } as never)
      .select(
        `
        *,
        author:profiles!blog_posts_author_id_fkey(
          id, username, display_name, avatar_url
        ),
        game:games!blog_posts_game_id_fkey(
          id, slug, name, icon_url
        )
      `
      )
      .single();

    if (postError) {
      console.error("Error creating blog post:", postError);
      return NextResponse.json(
        { error: "Failed to create post" },
        { status: 500 }
      );
    }

    return NextResponse.json({ post }, { status: 201 });
  } catch (error) {
    console.error("Blog creation error:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
